FROM nvidia/cuda:11.6.0-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y python3 python3-pip ipython3 && \
    pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116 && \
    apt-get install -y python3-gdal gdal-bin python3-geopandas python3-fiona python3-opencv python3-ipython python3-matplotlib python3-seaborn python3-scipy python3-shapely python3-geojson python3-boto3 python3-tqdm

RUN pip install tensorboard scikit-image geojson_rewind


RUN echo 'alias python=python3' >> ~/.bashrc && \
    echo 'alias pip=pip3' >> ~/.bashrc && \
    echo 'alias ipython=ipython3' >> ~/.bashrc



